version: '3.8'

services:
  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    networks:
      - ecommerce-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8080"
    networks:
      - ecommerce-network

  tracking-service:
    build: ./tracking-service
    ports:
      - "8083:8080"
    networks:
      - ecommerce-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - inventory-service
      - tracking-service
    networks:
      - ecommerce-network

  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - ecommerce-network


networks:
  ecommerce-network:
    driver: bridge
