version: '3.8'

services:
  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    networks:
      - ecommerce-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8080"
    networks:
      - ecommerce-network

  tracking-service:
    build: ./tracking-service
    ports:
      - "8083:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
